### ISSUE TITLE
Is there a way to obtain the business name using the API given an address/gps coordinate?

### ISSUE THREAD

**Issue by dpaulino** [Microsoft/BingMapsRESTToolkit#10]
I've been obsessively reading the [documentation ](https://msdn.microsoft.com/en-us/library/ff701713.aspx) for the REST API for the past few days but I have been unable to confirm if it's possible to obtain this information. Would someone be able to inform me if this is possible? Thanks in advance.

**Comment by dpaulino** [comment]
Would this be the correct API for what I'm asking? The Query API? https://msdn.microsoft.com/en-us/library/gg585126.aspx

**Comment by rbrundritt** [comment]
Yes, use the Query API with one of the NAVTEQ Data Sources: https://msdn.microsoft.com/en-US/library/hh478189.aspx If using .NET, take a look at the Spatial Data Services toolkit to make things easier: https://github.com/Microsoft/BingMapsSDSToolkit
