### ISSUE TITLE
A strongly-named assembly is required...

### ISSUE THREAD

**Issue by Hammarskjold** [microsoft/BingMapsRESTToolkit#12]
Can we get the BingMapsRESTToolkit.dll as a strongly named assembly by default?

Could not load file or assembly 'BingMapsRESTToolkit, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

I can fix this mysefl, but should be strongly named from source if possible?

Thx for a great API!

//A

**Comment by rbrundritt** [comment]
There are plans to do this, unfortunately the is a lot of red tape to go through at Microsoft to do this, thus the delay.

**Comment by brettmlewis** [comment]
Any update on this?  My problem is actually the SDS Toolkit, but I assume it's the same problem.

**Comment by IoTGirl** [comment]
Closing this as stale. We have no new assembly available at this point but you can build the nuget yourself from this public repo.
