### ISSUE TITLE
 JSON input is incorrect for non English culture

### ISSUE THREAD

**Issue by zhershds** [Microsoft/BingMapsRESTToolkit#14]
JSON input is incorrect for non English culture, for example "de-de".
Method GetPostRequestBody convert double coordinates to string using current culture. It can be the reason that double value can have ',' in string representation instead of '.'. As result distanceMatrixRequest.Execute throws exception "JSON input is incorrect".

**Comment by rbrundritt** [comment]
Thanks, we actually have an update planned today/tomorrow which includes a fix for this.

**Comment by rbrundritt** [comment]
The release with this fix is now available.
