### ISSUE TITLE
Add optional proxy to all HttpWebRequest calls in  (at least) ServiceHelper

### ISSUE THREAD

**Issue by josemdominguez** [Microsoft/BingMapsRESTToolkit#15]
Hello,
We all develop for users who work behind proxies and we need to make all calls using proxy.
Could you please add posiblity of proxy in ServiceHelper and BaseRestRequest calls?
Thanks,
Jose

**Comment by rbrundritt** [comment]
In the next update (January/February), there will be a static Proxy setting option on the ServiceManager class. You can set that once in your code and all requests executed afterwards will use those settings.

**Comment by rbrundritt** [comment]
Good news, a proxy setting has been added in the latest release 1.1.0. Simple add `ServiceManager.Proxy = [your proxy settings];` anywhere in your code before the library is used.
