### ISSUE TITLE
Example in Getting Started.md should be updated.

### ISSUE THREAD

**Issue by davefxy** [Microsoft/BingMapsRESTToolkit#17]
The following example with a single line changed I believe should be updated to:
//Create a request.
var request = new GeocodeRequest()
{
    Query = "New York, NY",
    IncludeIso2 = true,
    IncludeNeighborhood = true,
    MaxResults = 25,
    BingMapsKey = "YOUR_BING_MAPS_KEY"
};

var response = await request.Execute();

if(response != null && 
    response.ResourceSets != null && 
    response.ResourceSets.Length > 0 && 
    response.ResourceSets[0].Resources != null && 
    response.ResourceSets[0].Resources.Length > 0)
{
    var result = response.ResourceSets[0].Resources[0] as BingMapsRESTToolkit.Location;

    //Do something with the result.
}

**Comment by rbrundritt** [comment]
Updated. Thanks for reporting..
