### ISSUE TITLE
Allow for a starting point on travelling salesman

### ISSUE THREAD

**Issue by sethreidnz** [Microsoft/BingMapsRESTToolkit#19]
Is this possible? Looking at the source it is not but it would be a great addition if you could specify which way point you would like to start at.

**Comment by rbrundritt** [comment]
The first waypoint in the list should be used as the starting point.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sethreidnz** [comment]
Okay thanks will test it out! Appreciate the quick reply!

**Comment by rbrundritt** [comment]
I haven't soluble checked this today. If all else fails it is just a matter of shifting the circuit, but I believe I wrote code that already does that automatically.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
