### ISSUE TITLE
malformed URL request on ElevationRequest

### ISSUE THREAD

**Issue by allen-628** [Microsoft/BingMapsRESTToolkit#26]
I set up the ElevationRequest like this
ElevationRequest request = new ElevationRequest()
{
BingMapsKey = Properties.Settings.Default.API_Key,
Points = points,
Height = ElevationType.Ellipsoid
};
upon executing the response is: StatusDescription "Unauthorized"
The GetRequestUrl generated is: https://dev.virtualearth.net/REST/v1/Elevation/List?height=ellipsoid?key=API_Key&points=49,-103
The expected URL should be: https://dev.virtualearth.net/REST/v1/Elevation/List?points=49,-103&height=Ellipsoid&key=API_Key (or similar)

**Comment by Zulu-Inuoe** [comment]
Ditto. The relevant line is at

https://github.com/Microsoft/BingMapsRESTToolkit/blob/05f29a7fcd47f86006b590a70f0782025a09b05e/Source/Requests/ElevationRequest.cs#L242

I tried just changing "height=ellipsoid" to "heights=ellipsoid" and it works as expected
