### ISSUE TITLE
Calling RouteRequest from country with , as comma separator

### ISSUE THREAD

**Issue by SorenMuller** [Microsoft/BingMapsRESTToolkit#3]
Hi,

Thanks for at nice toolkit.. :-)

I have one issue though..
I have this simple code..
```
var req = new RouteRequest
{
   BingMapsKey = Mykey,
   Waypoints = new List<SimpleWaypoint>(2)
};
          
req.Waypoints.Add(new SimpleWaypoint { Address="loc1" ,Coordinate = new Coordinate(56.19825,10.22676)});
req.Waypoints.Add(new SimpleWaypoint { Address = "loc2", Coordinate = new Coordinate(56.1563,9.91033)});

var response = ServiceManager.GetResponseAsync(req).GetAwaiter().GetResult();

```

When I call this I get an error saying "One or more locations specified in the waypoint parameter are invalid or require more information."

After some digging and fiddler.. I figured out the the generated Url is using Danish comma notation, making it fails..

[http://dev.virtualearth.net/REST/v1/Routes/Driving?&wp.0=56,19825,10,22676&wp.1=56,1563,9,91033&key=mykey&clientApi=CSToolkit](url)

Is the any way to tell the toolkit to convert double to string with . as comma separator as needed ??
Thx

**Comment by rbrundritt** [comment]
Thanks for highlighting this. I've set the culture to invariant when generating the URL's. This should correct the issue. I have updated the nuget package (v1.0.3). Can you please test the latest package and verify if this issue is resolved.

**Comment by SorenMuller** [comment]
Hi Ricky,
It worked like a charm :-) 
Thanks alot for quick response :-)..

Best Regards 
Soren
