### ISSUE TITLE
new request like LocationRecogRequest not in nuget package?

### ISSUE THREAD

**Issue by pjthierry** [microsoft/BingMapsRESTToolkit#31]
I just started using de BingMapsRESTToolkit after installing it with the Nuget Pakage Manager in VS2017.
The problem I am having is that although it says version 1.1.4, it does not recognize the new Location Recognition and Time Zone API's. The also do not show in the Object Browser.
 Am I doing something wrong, or is there a problem with the package?
 
 thanks

**Comment by xuanyangge** [comment]
There is a problem with the package. I have contacted the owner and they promise to fix it. @v-chrfr

**Comment by IoTGirl** [comment]
@v-chrfr has left the team but the Bing Maps V8 team are looking at this component.

**Comment by RecursiveGeek** [comment]
There are a number of code changes made to this project that aren't in the 1.1.4 NuGet package (https://www.nuget.org/packages/BingMapsRESTToolkit) released on 3/10/2018.  For example, /Source/Requests/FindTimeZoneRequest.cs (which was added to GitHub on 8/29/2018.  When can we expect this to be changed?

**Comment by LyudPopov** [comment]
Any update on this issue?

**Comment by RecursiveGeek** [comment]
> Any update on this issue?

Hi @LyudPopov - we gave up and forked our own to add missing items we needed.  In case you are interested, https://github.com/daikinapplied/BingMapsRESTToolkit

**Comment by rbrundritt** [comment]
I just did a big update to this project and added in all missing services and fixed all logged bugs. This is available in version 1.1.5 (you can add this as a local project in your solution, not sure who updates the NuGet these days).

**Comment by BramMusters** [comment]
@rbrundritt
Thanks for updating the repository! Any news on the NuGet packager? Or is there any chance you could upload the dll's in the Github Releases section? I'm having trouble building the source code myself on a Mac. Thanks in advance

**Comment by IoTGirl** [comment]
I have no news for a new Nuget package but the original issue for this request has been fulfilled.
