### ISSUE TITLE
Passing Through The Enum Of distanceUnit Causes A 400 Response

### ISSUE THREAD

**Issue by saffbran** [microsoft/BingMapsRESTToolkit#39]
Making sure that the response is in miles and not kilometers, you pass the parameter of distanceUnit, and the enum included with the toolkit uses "Miles". This causes a 400 error because the proper parameter that should be passed is "mile" or "mi".

**Comment by rbrundritt** [comment]
This has been fixed in version 1.1.5 (you can add this as a local project in your solution, not sure who updates the NuGet these days).
