### ISSUE TITLE
ServiceHelper - No Exception Raised when WebException catched without response

### ISSUE THREAD

**Issue by DimitriSerca** [Microsoft/BingMapsRESTToolkit#4]
Hi,

Thank you for this userfull project.

I've got a problem.

For example, 
if internet if off, in ServiceHelper.GetStreamAsync(...) a WebException will be catched.
Cause ex.Response will be null, no tcs.SetException(ex) nor no tcs.SetResult(null) will be done.

In my code : 
`       
 private async void Button_Click(object sender, RoutedEventArgs e)
        {
            latitude.Text = string.Empty;
            longitude.Text = string.Empty;

            try
            {

                //Create a request.
                var request = new GeocodeRequest()
                {
                    Culture = "fr",
                    Query = tbAdresse.Text,
                    BingMapsKey = "MY KEY"
                };

                //Process the request by using the ServiceManager.
                Response response = await ServiceManager.GetResponseAsync(request);

                ; // Will be never reached if Internet is OFF, or can't contact server

                if (response != null &&
                    response.ResourceSets != null &&
                    response.ResourceSets.Length > 0 &&
                    response.ResourceSets[0].Resources != null &&
                    response.ResourceSets[0].Resources.Length > 0)
                {
                    var result = response.ResourceSets[0].Resources[0] as BingMapsRESTToolkit.Location;

                    latitude.Text = result.Point.Coordinates[0].ToString();
                    longitude.Text = result.Point.Coordinates[1].ToString();
                    //Do something with the result.
                }
            }
            catch (Exception ex)
            {
                ; // Will be never reached if Internet is OFF, or can't contact server

                MessageDialog msg = new MessageDialog(ex.Message);
                await msg.ShowAsync();
            }

            MessageDialog msgEnd = new MessageDialog("Finished");
            await msgEnd.ShowAsync();
        }
`
You can see piece of code that will be never reached 

Can you do Something ?

Thanks in advance
.

**Comment by rbrundritt** [comment]
Thanks for reporting. Found the issue and updated the code and NuGet package with a fix.

**Comment by DimitriSerca** [comment]
Hi,
Thank you for your quick action :-)
Regards,
Dimitri
