### ISSUE TITLE
Truck Route timeWithTraffic does not work

### ISSUE THREAD

**Issue by satbirsandhu** [microsoft/BingMapsRESTToolkit#42]
I am trying to get traffic time for the Truck route, it provides me time but does not account for traffic. 
(<any>directionsManager).setRequestOptions({
        routeMode: (<any>Microsoft.Maps.Directions.RouteMode).truck,
Microsoft.Maps.Directions.RouteOptimization.timeWithTraffic

I works for when routeMode set to driving but does not work for truck routeMode

**Comment by IoTGirl** [comment]
Please provide sample calls that show your issue. We can't debug without the ability to reproduce the issue.  Also, for issues with the base API, please report such issues at [https://social.msdn.microsoft.com/Forums/en-US/home?category=bingmaps](https://social.msdn.microsoft.com/Forums/en-US/home?category=bingmaps)

**Comment by satbirsandhu** [comment]
I cannot get timeWithTraffic in getRouteResult for the truck route.

Here is the request

   1.
   2. waypoints: [{latitude: 43.638145, longitude: -79.75599}, {latitude:
   43.641713, longitude: -79.376978}]
   3. routeAttributes: "routePath"
   4. vehicleSpec: {dimensionUnit: "ft", weightUnit: "lb", vehicleHeight:
   5, vehicleWidth: 3.5, vehicleLength: 23,…}
   5. avoid: "minimizeTolls"
   6. optimize: "time"
   7. distanceUnit: "mi"

Here is response

   1. summary: n
      1. distance: 21.786517
      2. time: 1622



However to do get the traffic time in  _routeResult, but not as part for
getRouteResult.
_routeResult

   1. {routeSummary: Array(1), route: Array(1)}
      1. routeSummary: Array(1)
         1. 0: n
            1. distance: 24.840556
            2. northEast: n {latitude: 43.61344, longitude: -79.75677,
            altitude: 0, altitudeReference: -1}
            3. southWest: n {latitude: 43.67108, longitude: -79.37466,
            altitude: 0, altitudeReference: -1}
            4. time: 1961
            5. timeWithTraffic: 2767
            6. __proto__: Object
         2. length: 1
         3. __proto__: Array(0)


Thanks

Satbir

**Comment by topeju** [comment]
I can also confirm this issue. Sample code:

```C#
        public static void TruckRouteTest()
        {
            var request = new RouteRequest {
                BingMapsKey = _ApiKey,
                RouteOptions = new RouteOptions {
                    DateTime = DateTime.Now,
                    DistanceUnits = DistanceUnitType.Kilometers,
                    Optimize = RouteOptimizationType.TimeWithTraffic,
                    RouteAttributes = new System.Collections.Generic.List<RouteAttributeType> { RouteAttributeType.All },
                    TimeType = RouteTimeType.Departure,
                    TravelMode = TravelModeType.Truck,
                    VehicleSpec = new VehicleSpec {
                        DimensionUnit = DimensionUnitType.Meter,
                        WeightUnit = WeightUnitType.Kilogram,
                        VehicleHeight = 2,
                        VehicleWidth = 2,
                        VehicleLength = 6,
                        VehicleWeight = 3901,
                        VehicleAxles = 2,
                        VehicleSemi = false,
                        VehicleTrailers = 0,
                        VehicleMaxGradient = 45,
                        VehicleMinTurnRadius = 8,
                        VehicleAvoidCrossWind = false,
                        VehicleAvoidGroundingRisk = false,
                    }
                },
                Waypoints = new System.Collections.Generic.List<SimpleWaypoint> {
                    new SimpleWaypoint { Coordinate = new Coordinate { Latitude = 60.420559, Longitude = 22.458193} },
                    new SimpleWaypoint { Address = "Betaniankatu 12, Turku" }
                },
                UserLocation = new Coordinate { Latitude = 60.420559, Longitude = 22.458193},
            };
            var resources = GetResourcesFromRequest(request);

            foreach (var resource in resources)
            {
                Console.WriteLine((resource as Location).Name);
            }

            Console.ReadLine();
        }
```

The equivalent Bing Maps REST call (using GET) is `https://dev.virtualearth.net/REST/v1/Routes/Truck?wayPoint.1=60.420559,22.458193&waypoint.2=Betaniankatu 12, Turku&optimize=timeWithTraffic&routeAttributes=routePath,regionTravelSummary&dateTime=2021-03-24T22:03:00&distanceUnit=km&vehicleHeight=2&vehicleWidth=2&vehicleLength=6&vehicleWeight=3901&vehicleAxles=2&vehicleTrailers=0&vehicleSemi=false&vehicleMaxGradient=45&vehicleMinTurnRadius=8&vehicleAvoidCrossWind=false&vehicleAvoidGroundingRisk=false&key={{bingMapsApiKey}}` and that one works, so I believe the problem is with BingMapsRESTToolkit.

The C# code above works  if `TravelMode = TravelModeType.Driving`, but not with truck directions.
