### ISSUE TITLE
Sign package assembly

### ISSUE THREAD

**Issue by BerserkerDotNet** [microsoft/BingMapsRESTToolkit#50]
Hi, 
[BingMapsRESTToolkit.dll](https://github.com/microsoft/BingMapsRESTToolkit/blob/master/Source/BingMapsRESTToolkit.csproj#L39) is not signed. This causes issues when using it from projects that are signed. Is there a reason it is left not signed? If no, can make it signed.

Thanks.

**Comment by IoTGirl** [comment]
Duplicate of https://github.com/microsoft/BingMapsRESTToolkit/issues/12

**Comment by nakhtar-ntg** [comment]
Why was it closed? Any solution to signing the DLL or any other workaround? @IoTGirl
