### ISSUE TITLE
Example to render route result to UWP map

### ISSUE THREAD

**Issue by beatnikthedan** [microsoft/BingMapsRESTToolkit#51]
In the traveling salesman example it is using WPF.
Can you provide an example how to render the result to a UWP map?
Can't figure out how to do it and there is no information how to use this with UWP at all

**Comment by IoTGirl** [comment]
For UWP, we suggest you start with the [Map Control class](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Maps.MapControl?view=winrt-19041). At the bottom you will find a link to the related [Github Sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MapControl)  

For a specific example of routes and directions with the UWP Map Control please see [https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/routes-and-directions](https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/routes-and-directions)
