### ISSUE TITLE
Bing Maps REST API - No route was found for the waypoints provided

### ISSUE THREAD

**Issue by danielNewb** [microsoft/BingMapsRESTToolkit#52]
Hello everybody,

I'm using Bing maps REST API with asp.net and BingMapsRESTToolkit (https://github.com/microsoft/BingMapsRESTToolkit)

When I try to get routes between Brescia and Cremona it returns me no Route was found. 

Request: https://dev.virtualearth.net/REST/v1/Routes/Driving?&wp.0=Brescia%20BS&wp.1=Cremona%20CR&c=it-IT&key={myPrivateKey}&clientApi=CSToolkit 

Response: 

{"authenticationResultCode":"ValidCredentials","brandLogoUri":"http:\/\/dev.virtualearth.net\/Branding\/logo_powered_by.png","copyright":"Copyright © 2020 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation.","errorDetails":["No route was found for the waypoints provided."],"resourceSets":[],"statusCode":404,"statusDescription":"Not Found"}

Why? If I search those location on bing maps https://www.bing.com/maps there are found results.

Somebody could help me?

Regards

**Comment by IoTGirl** [comment]
Hello Daniel,

This question is being addressed in the forums at [https://social.msdn.microsoft.com/Forums/en-US/home?category=bingmaps&filter=alltypes&sort=lastpostdesc&searchTerm=404](https://social.msdn.microsoft.com/Forums/en-US/home?category=bingmaps&filter=alltypes&sort=lastpostdesc&searchTerm=404).

Specifically there are two very different APIs; Bing.com/maps is using "Autosuggest" while the rest call is using a straight geocoder call that needs to disambiguate and is telling you that it can't find a unique value for a place with the text "Brescia" or "Cremona".  The good news is that you can assist the geocoder by providing just a little more detail such as "Brescia, Italy" and "Cremona, Italy" for example.

Sincerely,
IoTGirl
