### ISSUE TITLE
GetElevationCoordinates for a BoundingBox returns list of coordinates some of which are null

### ISSUE THREAD

**Issue by shochwald-maptek** [microsoft/BingMapsRESTToolkit#55]
When ElevationRequest.GetElevationCoordinates is called for a request that specifies equally-spaced locations within a bounding box, some of the coordinates returned are null because the coordinate index is calculated incorrectly.

Line

`int idx = r * row + c;`

should read

`int idx = r * cell + c;`

**Comment by rbrundritt** [comment]
I believe you meant `col` instead of `cell`. I've made this change locally and will check in soon.

**Comment by rbrundritt** [comment]
This has been fixed in version 1.1.5 (you can add this as a local project in your solution, not sure who updates the NuGet these days).
