### ISSUE TITLE
Scalebar is missing

### ISSUE THREAD

**Issue by vibalani** [microsoft/BingMapsRESTToolkit#59]
Hi,

I am using Bing maps to generate a static image and I am not able to find property to enable scalebar. Is it available if I use Bing maps to get the request and stream using Service Manager. Please find the details below:

Workflow:
1. Get request using BingMapsRESTToolkit.ImageryRequest

![image](https://user-images.githubusercontent.com/68795158/154757527-e67252b4-0767-4786-8504-7aba032f4d47.png)

2. Use the request from #1 and call service manager to return stream
![image](https://user-images.githubusercontent.com/68795158/154757668-0e37184c-e261-415f-89a9-9b800da01d8c.png)

3. Get background map image out of stream
![image](https://user-images.githubusercontent.com/68795158/154757889-fef9b008-e1a7-4288-b53c-af23d2f1c3cb.png)

4. Below is the sample output which is missing scale bar. 

![image](https://user-images.githubusercontent.com/68795158/154758259-da165bb6-f5a0-4c3b-8111-8855403c94dd.png)

Please let me know if I am not using the correct settings or function call or is it not supported yet. Thank you in advance!!

**Comment by rbrundritt** [comment]
The Bing Maps static image service doesn't have an option to add a scalebar, thus this service wrapper doesn't expose such a feature. (Docs: https://docs.microsoft.com/en-us/bingmaps/rest-services/imagery/get-a-static-map)

That said, if you know the zoom level and center coordinate of the map image, a scale could be calculated and a scalebar added using a drawing library. If you want to explore this route, here is an old blog I wrote that does something similar via WPF: https://rbrundritt.wordpress.com/2014/10/09/multiple-measurement-scale-bar-in-wpf/ The drawing/UX part would be different, but the math would be the same.

**Comment by vibalani** [comment]
rbrundritt - thank you so much for your reply and help!!

**Comment by rbrundritt** [comment]
Not sure on that one. It would depend on how you are creating the scale bars. If doing this in XAML, it's possible there is some "best fit" scaling happening of the control.
