### ISSUE TITLE
Coding Error?

### ISSUE THREAD

**Issue by sojatay** [Microsoft/BingMapsRESTToolkit#6]
Fabulous project overall. It's saved me a huge amount of time. Thank you!

I think there might be an error in RouteMajorRoadsRequest.cs

Lines 108 - 111 don't seem right:
           if (DistanceUnits == DistanceUnitType.KM)
            {
                url += "&distanceUnit=mi";
            }

Should this perhaps be: 

108............ if (DistanceUnits != DistanceUnitType.KM)

or

110........  url += "&distanceUnit=km";

**Comment by rbrundritt** [comment]
Yup, should be:

108............ if (DistanceUnits != DistanceUnitType.KM)

Checked in a fix and update the nuget package. Thanks for reporting.

**Comment by sojatay** [comment]
What amazing service! Thank you!
