### ISSUE TITLE
ElevationRequest returning only one value 

### ISSUE THREAD

**Issue by smarteez17** [Microsoft/BingMapsRESTToolkit#63]
Looking at the below code why is are we taking the first value ? 

**var elevation = elevResult.Elevations[0];**

Also I see that from the documents elevation is an array . My question is why am I only getting one value back ?
![image](https://user-images.githubusercontent.com/35128168/158433091-d12d48d4-2b63-456d-84f8-54593714d0c7.png)

//Create an elevation request for the geocoded coordinates.
	var elevRequest = new ElevationRequest()
	{
		Points = new List<Coordinate>() {
			coordinate
		},
		BingMapsKey = BING_MAPS_KEY
	};
	
	//Process the request by using the ServiceManager.
	var elevResponse = await elevRequest.Execute();
	
	if(elevResponse != null && 
		elevResponse.ResourceSets != null && 
		elevResponse.ResourceSets.Length > 0 && 
		elevResponse.ResourceSets[0].Resources != null && 
		elevResponse.ResourceSets[0].Resources.Length > 0)
	{
		var elevResult = elevResponse.ResourceSets[0].Resources[0] as BingMapsRESTToolkit.ElevationData;
	
		//Extract the elvation information.
		var elevation = elevResult.Elevations[0];
		
		//Do something with the coordinate and elevation information.
	
	} else {
		//Unable to find an elevation for a location. This often happens if the coordinate is over water.
	}

**Comment by rbrundritt** [comment]
That's just showing how to get the first value out. You can loop through it if you want. In the code sample I provided you in the other thread, where you copied this from, the sample geocoded a single location, and used that to get the elevation, thus there would only be one elevation result.
