### ISSUE TITLE
Compatibility to .net Core 1.1

### ISSUE THREAD

**Issue by oerpli** [Microsoft/BingMapsRESTToolkit#7]
I'm currently trying out .net core, using the (at least I think so) current version and get the following error:

`Package BingMapsRESTToolkit 1.0.5 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1)`

According to the readme this package should be compatible with ASP.NET Core 1.0 and as far as I understand the .net framework (which is not very far but still) asp.net core and dotnet core should be kind of similar/identical so it should work. 

Steps to reproduce:

- Install .net core from here https://www.microsoft.com/net/core#windowsvs2017 (command line tools)
- Create new app (`dotnet new console`)
- Add BingMapsRESTToolkit package from nuget to project (` dotnet add package BingMapsRESTToolkit`)

Full error message:

```
  Writing [...]\tmp3363.tmp
info : Adding PackageReference for package 'BingMapsRESTToolkit' into project '[...].csproj'.
log  : Restoring packages for [...].csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/bingmapsresttoolkit/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/bingmapsresttoolkit/index.json 623ms
info :   GET https://api.nuget.org/v3-flatcontainer/bingmapsresttoolkit/1.0.5/bingmapsresttoolkit.1.0.5.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/bingmapsresttoolkit/1.0.5/bingmapsresttoolkit.1.0.5.nupkg 502ms
log  : Installing BingMapsRESTToolkit 1.0.5.
error: Package BingMapsRESTToolkit 1.0.5 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package BingMapsRESTToolkit 1.0.5 supports:
error:   - dotnet (.NETPlatform,Version=v5.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
error:   - uap10.0 (UAP,Version=v10.0)
error:   - wpa81 (WindowsPhoneApp,Version=v8.1)
error:   - xamarinios (Xamarin.iOS,Version=v0.0)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.1.
error: Package 'BingMapsRESTToolkit' is incompatible with 'all' frameworks in project '[...]csproj'.
```

**Comment by rbrundritt** [comment]
.NET core is not supported at this time.

**Comment by oerpli** [comment]
Is there a technical reason for this (missing/incompatible APIs or similar) or only lack of demand?

**Comment by rbrundritt** [comment]
Main reasons; 

- Lack of demand (only 2 requests for this so far)
- .NET Core vs .NET Standard clarity. General consensus the last I looked was that these weren't where they need to be yet and likely won't be for about 4 to 6 months or so.
- Time. Don't have a lot of time to work on this. I recently had another portable class library where I added support for .NET standard. It took several hours to get working right and in the end consisted of creating a separate .NET standard project which was ugly.

**Comment by gecko-8** [comment]
Consider this another request.

**Comment by rbrundritt** [comment]
We will take a look at adding an .NET core library and see if we can get it in with our next planned update of this project near the end of September.

**Comment by atrauzzi** [comment]
What's the status of this?  I need to be able to use this library in .net core.

**Comment by rbrundritt** [comment]
Try the latest version. Support for .NET standard 1.4+ was added. If all else fails, simply download the source code and add it to your project.
