### ISSUE TITLE
Warning datamember in the JSON contract for a route is missing an 's'

### ISSUE THREAD

**Issue by Nightowl456** [Microsoft/BingMapsRESTToolkit#8]
I believe the DataMember that returns the warning information on an ItineraryItem is missing an s.

In RestServiceModels.cs, the line:

`        [DataMember(Name = "warning", EmitDefaultValue = false)]
        public Warning[] Warning { get; set; }
`
Should be (note the s at the end of the Name.  Up to you if you think Warning should be plural as well.)
`        [DataMember(Name = "warnings", EmitDefaultValue = false)]
        public Warning[] Warning { get; set; }
`

To recreate: In the REST Service Toolkit Test app, change the route waypoint(s) in the RouteBtn_Clicked routine to reflect a route that will have a Warning included. (Test by routing it on maps.bing.com - things like crossing a state boundary, traffic congestion, unpaved road, etc.). Note that there are no Warning-s in the returned Route. However, if you paste the raw REST call in your browser, you will see the warning information included in the raw output.

**Comment by rbrundritt** [comment]
Thanks for reporting. I've fixed this locally and will push this out in the next update in a few weeks.

**Comment by rbrundritt** [comment]
This is now fixed in the latest release 1.0.6.
