### ISSUE TITLE
System.IO Not Found

### ISSUE THREAD

**Issue by AntLaC** [Microsoft/BingMapsRESTToolkit#9]
In my project I'm targeting .NET 4.7. I'm not using Core. Looks like there is a conflict in versions. I downloaded the source code changed the target to 4.7 and didn't make it portable. Works like a charm that way.

**Comment by rbrundritt** [comment]
Thanks. I'll take a look at seeing if I can modify the NuGet package to support this the next time we update this library (~within the next month).

**Comment by rbrundritt** [comment]
I'm not able to reproduce this issue using the latest version of this library.
